services:
  sorare-lineup-optimizer:
    build: .
    container_name: sorare-lineup-optimizer
    ports:
      - "8080:8080"
    volumes:
      - /database:/app/database
      - ./lineups:/app/lineups
    restart: unless-stopped
    environment:
      - PORT=5000
      - DATABASE_PATH=/app/database/mlb_sorare.db
      - SELENIUM_HEADLESS=true