services:
  sorare-lineup-optimizer:
    build: .
    container_name: sorare-lineup-optimizer
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - PORT=5000
      - SELENIUM_HEADLESS=true
    depends_on:
      - db
    networks:
      - appnet

  db:
    image: postgres:17
    restart: always
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - appnet
    
    
volumes:
  pgdata:

networks:
  appnet: