services:
  sorare-lineup-optimizer:
    build: .
    container_name: sorare-lineup-optimizer
    ports:
      - "8080:8080"
    volumes:
      - ./mlb_sorare.db:/app/mlb_sorare.db
      - ./lineups:/app/lineups
    restart: unless-stopped
    environment:
      - PORT=5000
      - SELENIUM_HEADLESS=true